### PR TITLE
Make it easier to vulcanize all iron elements

### PR DESCRIPTION
**Pull request by krainboltgreene**
This gives an easy entrypoint for pulling in all iron element components, both in the regular import way and as a vulcanize target.

### CODE REVIEW

**Comment by krainboltgreene** [comment]
I signed it!

**Comment by adalinesimonian** [comment]
+1 - though I would consider naming it something less vulcanize-specific, such as `iron-elements.html`, because that would be less odd of a usage for the use-case described in http://stackoverflow.com/questions/30652584/polymer-1-0-import-all-elements-at-once

Perhaps I am a little biased. :wink:

**Comment by krainboltgreene** [comment]
@vsimonian I agree! `*-elements.html` makes a lot more sense.

**Comment by ebidel** [comment]
1. `bower_components` shouldn't be in the path. The paths should take the form https://github.com/Polymer/core-elements/blob/master/core-elements.html
2. +`to using`iron-elements.html`

TBH, I'm not sure why we don't have these aggregated imports in iron-elements and paper-elements. I think one issue may be that we still see people importing a lot more elements than they need. Not having these aggregated imports prevents people from going down that road.

**Comment by adalinesimonian** [comment]
I think the issue isn't so much for deployment as much as for rapid prototyping. I can definitely attest to having saved a lot of time just importing everything and playing with it, and then picking out what elements I need and explicitly importing them once I'm satisfied with my prototype. It becomes tedious to manage a list of imports when you're experimenting or testing things out.

**Comment by cdata** [comment]
I'm closing this for now. Please re-open if you think this should be considered again!

**Pull request closed without merging**
