### PR TITLE
Cleanup description in `bower.json`

### LINKED ISSUE #10: Trim description
The current version of Bower invalid any package with a [description longer than 140 characters](https://github.com/bower/json/blob/cbadab875639e7c65f8c51b34311bcae142a8066/lib/json.js#L107-L109). Any chance to trim the description of this package to make it a valid Bower JSON?

Thanks!

### PR DESCRIPTION
**Pull request by arthurvr**
Trims the description in the `bower.json` file to a valid length (it's 135 now).

Fix #10

### CODE REVIEW

**Comment by arthurvr** [comment]
Seems like the CI failure is unrelated.

**Comment by addyosmani** [comment]
lgtm

**Comment by addyosmani** [comment]
Could you try rebasing?

**Comment by arthurvr** [comment]
Done.

**Comment by addyosmani** [comment]
:+1:

**Pull request closed without merging**
